name = "echo-worker"  # This is the name of your worker
type = "javascript"
account_id = "53587ff809e7fbb7aa06b727b605c720"
workers_dev = true

[vars]
NAME_ENTRY = "entry.2024628311"
EMAIL_ENTRY = "entry.175637587"
